Adding Celo Kenyan Shilling
celo-org/celo-token-list pull request #58
Opened 2024-05-23 16:18 UTC by amitchuapf

2024-05-23 18:07 UTC, Alex4CeloEcosystem approved these changes

2024-05-24 11:48 UTC, aaronmgdr requested changes

2024-05-24 11:48 UTC, aaronmgdr commented on celo.tokenlist.json
>      }
and here `;`

2024-05-24 16:33 UTC, nicolasbrugneaux commented on celo.tokenlist.json
>      }
```suggestion
    },
```

2024-05-24 16:33 UTC, nicolasbrugneaux commented on celo.tokenlist.json
> +    }
```suggestion
    },
```

2024-05-24 16:35 UTC, merged