Add PrideToken (PRD)
celo-org/celo-token-list pull request #69
Opened 2024-11-26 01:09 UTC by senegalbgc

This pull request adds the PrideToken (PRD) details to the Celo token list.  
  
## Token Information  
- **Name:** PrideToken  
- **Address:** `0xAE62Ca7e7Bc80C800DADc1c4b9175800033537cd`  
- **Symbol:** PRD  
- **Decimals:** 18  
- **Chain ID:** 42220  
- **Logo URI:** [PrideToken Logo](https://pridefunding.org/assets/PrideToken/PrideTokenbg.svg)  
  
Adding PrideToken to the Celo token list will ensure it is recognized across the Celo ecosystem, including wallets and dApps that rely on this token list. This will help users and integrators access accurate and up-to-date information about PrideToken.

2024-11-27 11:24 UTC, aaronmgdr requested changes
can you verify the  token contract on celoscan or with sourcify? 

and are there any docs on how the token economics function?

2024-11-27 23:52 UTC, senegalbgc commented
Hi @aaronmgdr,  
  
We have updated the pull request with the correct deployment address for the PrideToken (PRD) contract.  
  
**Updated Token Information:**  
- **Name:** PrideToken  
- **Address:** `0x1B0b2647Fc522417d79d8080F9D41977f03D3C46`  
- **Symbol:** PRD  
- **Decimals:** 18  
- **Chain ID:** 42220  
- **Logo URI:** [PrideToken Logo](https://pridefunding.org/assets/PrideToken/PrideTokenbg.svg)  
  
**Verification Details:**  
- **Contract Name:** PrideToken  
- **Network:** Celo Mainnet  
- **Contract Address:** [0x1B0b2647Fc522417d79d8080F9D41977f03D3C46](https://sourcify.dev/#/lookup/0x1B0b2647Fc522417d79d8080F9D41977f03D3C46)  
- **Verification Link:** [Sourcify Verification](https://sourcify.dev/#/lookup/0x1B0b2647Fc522417d79d8080F9D41977f03D3C46)  
  
### Token Economics Documentation  
Please find the detailed token economics documentation in our GitHub repository: [TOKENOMICS.md](https://github.com/senegalbgc/pride-token-list/blob/main/TOKENOMICS.md)  
  
Let us know if you need anything else.

2024-12-02 08:58 UTC, aaronmgdr commented
the address in the pr 0xAE62Ca7e7Bc80C800DADc1c4b9175800033537cd doesnt match the description or the sourcify link

2024-12-02 21:53 UTC, senegalbgc commented
@aaronmgdr here: 

Name: PrideToken
Address: 0x1B0b2647Fc522417d79d8080F9D41977f03D3C46
Symbol: PRD
Decimals: 18
Chain ID: 42220

Logo URI: [PrideToken Logo](https://pridefunding.org/assets/PrideToken/PrideTokenbg.svg)

**Verification Links:**  
- [Etherscan](https://etherscan.io/address/0xAE62Ca7e7Bc80C800DADc1c4b9175800033537cd#code)  
- [Celo Explorer (Sourcify)](https://sourcify.dev/#/lookup/0xAE62Ca7e7Bc80C800DADc1c4b9175800033537cd)  
- [BscScan](https://bscscan.com/address/0xAE62Ca7e7Bc80C800DADc1c4b9175800033537cd#code) 
- 
Let me know if there is anything else you need.

2024-12-03 08:08 UTC, aaronmgdr commented on celo.tokenlist.json
> +
```suggestion
}
```

2024-12-03 08:08 UTC, aaronmgdr commented on celo.tokenlist.json
> +
```suggestion
}
```

2024-12-03 08:09 UTC, aaronmgdr commented on celo.tokenlist.json
> +
```suggestion
}

2024-12-03 08:09 UTC, aaronmgdr approved these changes
🌈

2024-12-03 08:09 UTC, merged

2024-12-04 02:11 UTC, senegalbgc commented
Thanks @aaronmgdr!
Natty